<a href="https://colab.research.google.com/github/melekbairamova20/Python-Miuul/blob/main/PandasNumPy_Miuul.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python ile veri analizi

NumPy

In [1]:
import numpy as np


In [4]:
l1 = [1,2,3,4,5]
l2 = [11,12,13,14,15]
print(l1)
print(l2)

[1, 2, 3, 4, 5]
[11, 12, 13, 14, 15]


In [6]:
lst = []
for i in range(0, len(l1)):
  lst.append(l1[i]*l2[i])
print(lst)



[11, 24, 39, 56, 75]


In [11]:
arr1 = np.array([2,21,3,35,25])
arr2 = np.array([34,23,16,78,45])
arr1 * arr2

array([  68,  483,   48, 2730, 1125])

In [15]:
lst = [65, 23, 12, 35, 67]
arr = np.array(lst)
arr

array([65, 23, 12, 35, 67])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.arange(0, 12, 3)  # 0-dan 12-ye qeder siralayir uc uc


array([0, 3, 6, 9])

In [23]:
np.random.randint(0, 100, 10)  # 0 ile 100 arasinda 10 dene number yazir random secir

array([64, 36, 81, 12, 45, 40, 33, 30,  8,  1])

In [29]:
np.random.normal(loc=0, scale=1, size=(2,3))  # normal dagilima gore 2*3 matrix yaradir

array([[-0.97642849, -0.14089009,  0.10046557],
       [ 1.38051803,  1.02845963,  0.67118705]])

In [30]:
np.linspace(0, 5, 10)  # 0 ile 5 arasinda 10 number

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [32]:
arr3 = np.arange(0,10,2)
arr3

array([0, 2, 4, 6, 8])

In [34]:
arr3.shape

(5,)

In [35]:
arr3.ndim

1

In [38]:
arr3.size # toplam reqem sayi

5

In [41]:
# randomlugu engellemek ucun random.seed(42) yazilir
np.random.seed(42)
arr4 = np.random.normal(loc=0, scale=1, size=(3,4))
arr4

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975]])

In [42]:
arr4.shape


(3, 4)

# Index selection

In [45]:
arr3[1:5] # 1-ci indexden basla 5-e qeder get

array([2, 4, 6, 8])

In [47]:
arr3[:3] #sifirinci setirden saymaga baslayir

array([0, 2, 4])

In [50]:
arr4[1:3] # setir sutun

array([[-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975]])

NumPy icerisinde tek veri tipi tutar

In [53]:
arr > 30


array([ True, False, False,  True,  True])

In [52]:
arr

array([65, 23, 12, 35, 67])

In [54]:
arr[arr > 30]

array([65, 35, 67])

In [56]:
arr[arr!=30]

array([65, 23, 12, 35, 67])

# Pandas

Pandas Series

In [57]:
import pandas as pd

In [59]:
arr = np.array([1,2,3,4,5,6,7])
ser = pd.Series(arr)
ser

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [60]:
ser.shape

(7,)

In [61]:
ser.ndim

1

In [63]:
ser.size

7

In [64]:
ser.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [65]:
ser.tail()

2    3
3    4
4    5
5    6
6    7
dtype: int64

In [66]:
import seaborn as sns


In [67]:
df = sns.load_dataset("tips")
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [68]:
type(df)

pandas.core.frame.DataFrame

In [69]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [70]:
df.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [71]:
pd.set_option('display.max_rows', None)

In [73]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

Veriye ilkin baxis

In [75]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [76]:
df.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [77]:
df.size

1708

In [80]:
df.shape

(244, 7)

In [82]:
df.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [85]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [86]:
df.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [87]:
df.isnull()

total_bill    tip    sex  smoker    day   time   size
0         False  False  False   False  False  False  False
1         False  False  False   False  False  False  False
2         False  False  False   False  False  False  False
3         False  False  False   False  False  False  False
4         False  False  False   False  False  False  False
5         False  False  False   False  False  False  False
6         False  False  False   False  False  False  False
7         False  False  False   False  False  False  False
8         False  False  False   False  False  False  False
9         False  False  False   False  False  False  False
10        False  False  False   False  False  False  False
11        False  False  False   False  False  False  False
12        False  False  False   False  False  False  False
13        False  False  False   False  False  False  False
14        False  False  False   False  False  False  False
15        False  False  False   False  False  False  False
16        False  False  False   False  False  False  False
17        False  False  False   False  False  False  False
18        False  False  False   False  False  False  False
19        False  False  False   False  False  False  False
20        False  False  False   False  False  False  False
21        False  False  False   False  False  False  False
22        False  False  False   False  False  False  False
23        False  False  False   False  False  False  False
24        False  False  False   False  False  False  False
25        False  False  False   False  False  False  False
26        False  False  False   False  False  False  False
27        False  False  False   False  False  False  False
28        False  False  False   False  False  False  False
29        False  False  False   False  False  False  False
30        False  False  False   False  False  False  False
31        False  False  False   False  False  False  False
32        False  False  False   False  False  False  False
33        False  False  False   False  False  False  False
34        False  False  False   False  False  False  False
35        False  False  False   False  False  False  False
36        False  False  False   False  False  False  False
37        False  False  False   False  False  False  False
38        False  False  False   False  False  False  False
39        False  False  False   False  False  False  False
40        False  False  False   False  False  False  False
41        False  False  False   False  False  False  False
42        False  False  False   False  False  False  False
43        False  False  False   False  False  False  False
44        False  False  False   False  False  False  False
45        False  False  False   False  False  False  False
46        False  False  False   False  False  False  False
47        False  False  False   False  False  False  False
48        False  False  False   False  False  False  False
49        False  False  False   False  False  False  False
50        False  False  False   False  False  False  False
51        False  False  False   False  False  False  False
52        False  False  False   False  False  False  False
53        False  False  False   False  False  False  False
54        False  False  False   False  False  False  False
55        False  False  False   False  False  False  False
56        False  False  False   False  False  False  False
57        False  False  False   False  False  False  False
58        False  False  False   False  False  False  False
59        False  False  False   False  False  False  False
60        False  False  False   False  False  False  False
61        False  False  False   False  False  False  False
62        False  False  False   False  False  False  False
63        False  False  False   False  False  False  False
64        False  False  False   False  False  False  False
65        False  False  False   False  False  False  False
66        False  False  False   False  False  False 

In [88]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [89]:
df["total_bill"].head()

0    16.99
1    10.34
2    21.01
3    23.68
4    24.59
Name: total_bill, dtype: float64

In [91]:
df["total_bill"].unique()

array([16.99, 10.34, 21.01, 23.68, 24.59, 25.29,  8.77, 26.88, 15.04,
       14.78, 10.27, 35.26, 15.42, 18.43, 14.83, 21.58, 10.33, 16.29,
       16.97, 20.65, 17.92, 20.29, 15.77, 39.42, 19.82, 17.81, 13.37,
       12.69, 21.7 , 19.65,  9.55, 18.35, 15.06, 20.69, 17.78, 24.06,
       16.31, 16.93, 18.69, 31.27, 16.04, 17.46, 13.94,  9.68, 30.4 ,
       18.29, 22.23, 32.4 , 28.55, 18.04, 12.54, 10.29, 34.81,  9.94,
       25.56, 19.49, 38.01, 26.41, 11.24, 48.27, 13.81, 11.02, 17.59,
       20.08, 16.45,  3.07, 20.23, 15.01, 12.02, 17.07, 26.86, 25.28,
       14.73, 10.51, 27.2 , 22.76, 17.29, 19.44, 16.66, 10.07, 32.68,
       15.98, 34.83, 13.03, 18.28, 24.71, 21.16, 28.97, 22.49,  5.75,
       16.32, 22.75, 40.17, 27.28, 12.03, 12.46, 11.35, 15.38, 44.3 ,
       22.42, 20.92, 15.36, 20.49, 25.21, 18.24, 14.31, 14.  ,  7.25,
       38.07, 23.95, 25.71, 17.31, 29.93, 10.65, 12.43, 24.08, 11.69,
       13.42, 14.26, 15.95, 12.48, 29.8 ,  8.52, 14.52, 11.38, 22.82,
       19.08, 20.27,

In [93]:
df["total_bill"].value_counts()

total_bill
13.42    3
21.01    2
20.69    2
10.33    2
10.34    2
20.29    2
10.07    2
13.81    2
18.29    2
15.98    2
15.69    2
7.25     2
17.92    2
13.00    2
35.26    1
14.83    1
18.43    1
15.42    1
24.59    1
16.99    1
23.68    1
20.65    1
16.97    1
39.42    1
15.77    1
17.81    1
13.37    1
12.69    1
19.82    1
21.70    1
19.65    1
18.35    1
9.55     1
14.78    1
10.27    1
25.29    1
8.77     1
16.31    1
24.06    1
17.78    1
15.06    1
17.46    1
13.94    1
31.27    1
16.93    1
30.40    1
22.23    1
32.40    1
28.55    1
18.04    1
12.54    1
9.68     1
18.69    1
34.81    1
9.94     1
19.49    1
25.56    1
38.01    1
26.41    1
11.24    1
48.27    1
11.02    1
17.59    1
20.08    1
16.45    1
3.07     1
20.23    1
10.29    1
16.04    1
12.02    1
15.01    1
17.07    1
26.86    1
10.51    1
27.20    1
25.28    1
14.73    1
17.29    1
22.76    1
16.66    1
19.44    1
32.68    1
34.83    1
13.03    1
18.28    1
24.71    1
21.16    1
28.97    1
22.49    1
5.75     1
16.32    1
22.75    1
40.17    1
27.28    1
12.03    1
12.46    1
11.35    1
21.58    1
16.29    1
26.88    1
15.04    1
20.92    1
22.42    1
44.30    1
15.38    1
18.24    1
14.31    1
25.21    1
15.36    1
23.95    1
25.71    1
17.31    1
29.93    1
10.65    1
12.43    1
14.00    1
20.49    1
11.69    1
14.26    1
15.95    1
12.48    1
29.80    1
8.52     1
14.52    1
11.38    1
22.82    1
19.08    1
20.27    1
11.17    1
12.26    1
18.26    1
24.08    1
38.07    1
16.00    1
13.16    1
17.47    1
34.30    1
41.19    1
27.05    1
16.43    1
8.35     1
18.64    1
11.87    1
9.78     1
7.51     1
14.07    1
13.13    1
17.26    1
24.55    1
19.77    1
29.85    1
48.17    1
25.00    1
13.39    1
16.49    1
21.50    1
12.66    1
16.21    1
17.51    1
24.52    1
20.76    1
31.71    1
10.59    1
8.51     1
14.15    1
50.81    1
10.63    1
15.81    1
31.85    1
17.89    1
14.48    1
16.82    1
32.90    1
34.65    1
23.33    1
45.35    1
23.17    1
40.55    1
20.90    1
9.60     1
34.63    1
18.15    1
30.46    1
19.81    1
23.10    1
15.48    1
16.58    1
7.56     1
28.44    1
43.11    1
13.51    1
18.71    1
12.74    1
16.40    1
20.53    1
16.47    1
26.59    1
38.73    1
24.27    1
12.76    1
30.06    1
25.89    1
48.33    1
13.27    1
28.17    1
12.90    1
28.15    1
11.59    1
7.74     1
30.14    1
12.16    1
8.58     1
16.27    1
10.09    1
20.45    1
13.28    1
22.12    1
24.01    1
11.61    1
10.77    1
15.53    1
12.60    1
32.83    1
35.83    1
29.03    1
27.18    1
22.67    1
17.82    1
18.78    1
Name: count, dtype: int64

In [95]:
df[df["total_bill"]>10].head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [96]:
df["total_bill"]> 10

0       True
1       True
2       True
3       True
4       True
5       True
6      False
7       True
8       True
9       True
10      True
11      True
12      True
13      True
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
30     False
31      True
32      True
33      True
34      True
35      True
36      True
37      True
38      True
39      True
40      True
41      True
42      True
43     False
44      True
45      True
46      True
47      True
48      True
49      True
50      True
51      True
52      True
53     False
54      True
55      True
56      True
57      True
58      True
59      True
60      True
61      True
62      True
63      True
64      True
65      True
66      True
67     False
68      True
69      True
70      True
71      True
72      True
73      True
74      True
75      True
76      True
77      True
78      True
79      True
80      True
81      True
82      True
83      True
84      True
85      True
86      True
87      True
88      True
89      True
90      True
91      True
92     False
93      True
94      True
95      True
96      True
97      True
98      True
99      True
100     True
101     True
102     True
103     True
104     True
105     True
106     True
107     True
108     True
109     True
110     True
111    False
112     True
113     True
114     True
115     True
116     True
117     True
118     True
119     True
120     True
121     True
122     True
123     True
124     True
125     True
126    False
127     True
128     True
129     True
130     True
131     True
132     True
133     True
134     True
135    False
136     True
137     True
138     True
139     True
140     True
141     True
142     True
143     True
144     True
145    False
146     True
147     True
148    False
149    False
150     True
151     True
152     True
153     True
154     True
155     True
156     True
157     True
158     True
159     True
160     True
161     True
162     True
163     True
164     True
165     True
166     True
167     True
168     True
169     True
170     True
171     True
172    False
173     True
174     True
175     True
176     True
177     True
178    False
179     True
180     True
181     True
182     True
183     True
184     True
185     True
186     True
187     True
188     True
189     True
190     True
191     True
192     True
193     True
194     True
195    False
196     True
197     True
198     True
199     True
200     True
201     True
202     True
203     True
204     True
205     True
206     True
207     True
208     True
209     True
210     True
211     True
212     True
213     True
214     True
215     True
216     True
217     True
218    False
219     True
220     True
221     True
222    False
223     True
224     True
225     True
226     True
227     True
228     True
229     True
230     True
231     True
232     True
233     True
234     True
235     True
236     True
237     True
238     True
239     True
240     True
241     True
242     True
243     True
Name: total_bill, dtype: bool

#LOC

In [101]:
df.loc[0:3, "total_bill"]  # setir, sutun

0    16.99
1    10.34
2    21.01
3    23.68
Name: total_bill, dtype: float64

LOC ile filtrleme

In [102]:
df.loc[df["total_bill"]>10].head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [103]:
df.loc[df["total_bill"]> 10, "size"].head()

0    2
1    3
2    3
3    2
4    4
Name: size, dtype: int64

In [105]:
df.loc[df["total_bill"]> 10, ["smoker", "size"]].head()

smoker  size
0     No     2
1     No     3
2     No     3
3     No     2
4     No     4

# ILOC

In [107]:
df.iloc[0]

total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

In [108]:
df.iloc[0, 2:4]

sex       Female
smoker        No
Name: 0, dtype: object

In [109]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

# Aggregation Functions

Group by

In [110]:
df.groupby("day")["total_bill"].mean()

/tmp/ipython-input-2472984912.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("day")["total_bill"].mean()


day
Thur    17.682742
Fri     17.151579
Sat     20.441379
Sun     21.410000
Name: total_bill, dtype: float64

In [112]:
df.groupby("day").agg({
    "total_bill": "mean"
})

/tmp/ipython-input-2625485448.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("day").agg({


total_bill
day             
Thur   17.682742
Fri    17.151579
Sat    20.441379
Sun    21.410000

# Pivot Table

In [113]:
df.pivot_table(values="total_bill", index = "day", aggfunc = "mean")

/tmp/ipython-input-3307690723.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(values="total_bill", index = "day", aggfunc = "mean")


total_bill
day             
Thur   17.682742
Fri    17.151579
Sat    20.441379
Sun    21.410000

In [114]:
df.pivot_table(
    values=["total_bill", "tip"],
    index="day",
    aggfunc={
        "total_bill": ["mean", "sum"],
        "tip": "mean"
    }
)


/tmp/ipython-input-3722938997.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(


tip total_bill         
          mean       mean      sum
day                               
Thur  2.771452  17.682742  1096.33
Fri   2.734737  17.151579   325.88
Sat   2.993103  20.441379  1778.40
Sun   3.255132  21.410000  1627.16

In [115]:
def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.describe([0, 0.05, 0.50, 0.95, 0.99, 1]).T) # sayısal değişkenlerin dağılım bilgisi

In [116]:
check_df(df)

##################### Shape #####################
(244, 7)
##################### Types #####################
total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object
##################### Head #####################
   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
##################### Tail #####################
     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243      

In [117]:
cat_cols = ['sex', 'smoker', 'day', 'time']
def cat_summary(dataframe, col_name):
    print(pd.DataFrame({col_name: dataframe[col_name].value_counts(),
                        "Ratio": 100 * dataframe[col_name].value_counts() / len(dataframe)}))
    print("##########################################")


cat_summary(df, "day") # 1 değişkene bakmak için

      day      Ratio
day                 
Sat    87  35.655738
Sun    76  31.147541
Thur   62  25.409836
Fri    19   7.786885
##########################################


In [118]:
num_cols = ['total_bill', 'tip', 'size']
def num_summary(dataframe, numerical_col):
    quantiles = [0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 0.95, 0.99]
    print(dataframe[numerical_col].describe(quantiles).T)

num_summary(dataframe=df, numerical_col="tip")  # 1 değişkene bakmak için

count    244.000000
mean       2.998279
std        1.383638
min        1.000000
5%         1.440000
10%        1.500000
20%        2.000000
30%        2.000000
40%        2.476000
50%        2.900000
60%        3.016000
70%        3.480000
80%        4.000000
90%        5.000000
95%        5.195500
99%        7.214500
max       10.000000
Name: tip, dtype: float64


In [119]:
TARGET = "total_bill"
# Kategorik değişken ile hedef değişkenin ilişkisi
def target_summary_with_cat(dataframe, target, categorical_col):
    print(pd.DataFrame({"TARGET_MEAN": dataframe.groupby(categorical_col)[target].mean()}), end="\n\n\n")

for col in cat_cols:
    target_summary_with_cat(dataframe=df,
                            target=TARGET,
                            categorical_col=col)

        TARGET_MEAN
sex                
Male      20.744076
Female    18.056897


        TARGET_MEAN
smoker             
Yes       20.756344
No        19.188278


      TARGET_MEAN
day              
Thur    17.682742
Fri     17.151579
Sat     20.441379
Sun     21.410000


        TARGET_MEAN
time               
Lunch     17.168676
Dinner    20.797159




/tmp/ipython-input-3661104689.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(pd.DataFrame({"TARGET_MEAN": dataframe.groupby(categorical_col)[target].mean()}), end="\n\n\n")
/tmp/ipython-input-3661104689.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(pd.DataFrame({"TARGET_MEAN": dataframe.groupby(categorical_col)[target].mean()}), end="\n\n\n")
/tmp/ipython-input-3661104689.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default an